name: Automated E2E Testing
on: 
  pull_request:
  workflow_dispatch:
  
env:
  USER_EMAIL: ${{secrets.USER_EMAIL}}
  USER_PASSWORD: ${{secrets.USER_PASSWORD}}
  
jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci
        
      - name: Set Cypress environment variables
        run: echo "CYPRESS_USER_EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
      
      - name: Display CYPRESS_USER_EMAIL
        run: echo "CYPRESS_USER_EMAIL=${CYPRESS_USER_EMAIL}"

          
      - name: Run Cypress tests with Electron
        uses: cypress-io/github-action@v6
        with:
          browser: electron
  
